import json

# Read the notebook file
with open('task2_notebook/task2_improved.ipynb', 'r') as f:
    data = json.load(f)

# Define the new source code with enhanced error handling
new_source_lines = [
    "# Define dataset paths",
    'DATA_DIR = "../t_ecd_small_partial/dataset/small"',
    'BRANDS_PATH = f"{DATA_DIR}/brands.pq"',
    'USERS_PATH = f"{DATA_DIR}/users.pq"',
    'ITEMS_PATH = f"{DATA_DIR}/marketplace/items.pq"',
    'EVENTS_DIR = f"{DATA_DIR}/marketplace/events"',
    "",
    "# Load static files",
    "try:",
    "    # Load brands data with enhanced error handling",
    '    print("Attempting to load brands data...")',
    "    brands_df = pd.read_parquet(BRANDS_PATH, engine='pyarrow')",
    '    print(f"Loaded brands data: {brands_df.shape}")',
    "except Exception as e:",
    '    print(f"Error loading brands data: {e}")',
    '    print("Attempting alternative loading methods...")',
    "    ",
    "    # Try loading with fastparquet engine",
    "    try:",
    '        print("Trying fastparquet engine...")',
    "        brands_df = pd.read_parquet(BRANDS_PATH, engine='fastparquet')",
    '        print(f"Loaded brands data with fastparquet: {brands_df.shape}")',
    "    except Exception as e2:",
    '        print(f"Error loading brands data with fastparquet: {e2}")',
    "        ",
    "        # Try loading specific columns only (avoiding problematic embedding column)",
    "        try:",
    '            print("Trying to load specific columns only...")',
    "            # First, try to read just the schema to understand the structure",
    "            import pyarrow.parquet as pq",
    "            try:",
    "                schema = pq.read_schema(BRANDS_PATH)",
    '                print(f"Available columns: {schema.names}")',
    "                ",
    "                # Load only non-embedding columns",
    "                non_embedding_columns = [col for col in schema.names if 'embedding' not in col.lower()]",
    '                print(f"Loading columns: {non_embedding_columns}")',
    "                ",
    "                brands_df = pd.read_parquet(BRANDS_PATH, engine='pyarrow', columns=non_embedding_columns)",
    '                print(f"Loaded brands data with selected columns: {brands_df.shape}")',
    "            except Exception as e3:",
    '                print(f"Error reading schema or loading selected columns: {e3}")',
    "                ",
    "                # Last resort: try to load with error handling for inconsistent list sizes",
    "                try:",
    '                    print("Attempting to load with pyarrow-specific options...")',
    "                    # Try loading with different options that might handle the inconsistent data",
    "                    import pyarrow as pa",
    "                    table = pq.read_table(BRANDS_PATH)",
    "                    brands_df = table.to_pandas()",
    '                    print(f"Loaded brands data with pyarrow table conversion: {brands_df.shape}")',
    "                except Exception as e4:",
    '                    print(f"Error loading brands data with pyarrow table conversion: {e4}")',
    '                    print("Could not load brands data with any method. Setting to None.")',
    "                    brands_df = None",
    "        except Exception as e5:",
    '            print(f"Error in alternative loading approaches: {e5}")',
    '            print("Could not load brands data. Setting to None.")',
    "            brands_df = None",
    "",
    "try:",
    "    # Load users data",
    "    users_df = pd.read_parquet(USERS_PATH, engine='fastparquet')",
    '    print(f"Loaded users data: {users_df.shape}")',
    "except Exception as e:",
    '    print(f"Error loading users data: {e}")',
    "    users_df = None",
    "",
    "try:",
    "    # Load items data",
    "    items_df = pd.read_parquet(ITEMS_PATH, engine='fastparquet')",
    '    print(f"Loaded items data: {items_df.shape}")',
    "except Exception as e:",
    '    print(f"Error loading items data: {e}")',
    "    items_df = None",
    "",
    "# Load event files",
    "import os",
    "",
    "try:",
    "    event_files = sorted([f for f in os.listdir(EVENTS_DIR) if f.endswith('.pq')])",
    '    print(f"Found {len(event_files)} event files")',
    "except Exception as e:",
    '    print(f"Error accessing events directory: {e}")',
    "    event_files = []",
    "",
    "event_dataframes = []",
    "for file in event_files[:5]:  # Load first 5 for demonstration",
    "    try:",
    "        file_path = os.path.join(EVENTS_DIR, file)",
    "        df = pd.read_parquet(file_path, engine='fastparquet')",
    "        event_dataframes.append(df)",
    "        if len(event_dataframes) % 5 == 0:",
    '            print(f"Loaded {len(event_dataframes)} event files...")',
    "    except Exception as e:",
    '        print(f"Error loading event file {file}: {e}")',
    "",
    "if event_dataframes:",
    "    events_df = pd.concat(event_dataframes, ignore_index=True)",
    '    print(f"Combined events data: {events_df.shape}")',
    "else:",
    '    print("No event data loaded")',
    "    events_df = None",
    "",
    "# Display basic information about datasets",
    "if brands_df is not None:",
    '    print("\\n--- BRANDS DATASET ---")',
    '    print(f"Shape: {brands_df.shape}")',
    '    print(f"Columns: {list(brands_df.columns)}")',
    "    print(brands_df.head())",
    "",
    "if users_df is not None:",
    '    print("\\n--- USERS DATASET ---")',
    '    print(f"Shape: {users_df.shape}")',
    '    print(f"Columns: {list(users_df.columns)}")',
    "    print(users_df.head())",
    "",
    "if items_df is not None:",
    '    print("\\n--- ITEMS DATASET ---")',
    '    print(f"Shape: {items_df.shape}")',
    '    print(f"Columns: {list(items_df.columns)}")',
    "    print(items_df.head())",
    "",
    "if events_df is not None:",
    '    print("\\n--- EVENTS DATASET ---")',
    '    print(f"Shape: {events_df.shape}")',
    '    print(f"Columns: {list(events_df.columns)}")',
    "    print(events_df.head())"
]

# Update the source code in cell 3
data['cells'][3]['source'] = new_source_lines

# Write the modified data back to the file
with open('task2_notebook/task2_improved.ipynb', 'w') as f:
    json.dump(data, f, indent=1)

print("Successfully modified the brands data loading code in cell 3 with proper formatting")
